const CONSTANTS = {
    GAME_LOGIC_TIME_INTERVAL_IN_MILLISECONDS: 100,

    FIELD_LEFT: 0,
    FIELD_TOP: 0,
    FIELD_WIDTH: 700,
    FIELD_HEIGHT: 400,

    SNAKE_STARTING_X: 350,
    SNAKE_STARTING_Y: 200,
    SNAKE_STARTING_LENGTH: 10,
    SNAKE_SIZE: 20,
    // TODO: Refactor
    SNAKE_SPEED: 21,
    SNAKE_DEFAULT_FILL_STYLE: fillStyles.fill,
    SNAKE_DEFAULT_SEGMENT_TYPE: segmentTypes.rectangle,

    FEED_SIZE: 10,
    FEED_DEFAULT_FILL_STYLE: fillStyles.fillAndStroke,
    FEED_DEFAULT_TYPE: feedTypes.sphere
};