const CONSTANTS = {
    FRAME_TIME_INTERVAL_IN_MILLISECONDS: 25,

    FIELD_LEFT: 0,
    FIELD_TOP: 0,
    FIELD_WIDTH: 700,
    FIELD_HEIGHT: 400,

    SNAKE_STARTING_X: 350,
    SNAKE_STARTING_Y: 200,
    SNAKE_STARTING_LENGTH: 10,
    SNAKE_SPEED: 5,
    SNAKE_SIZE: 20,
    SNAKE_DEFAULT_FILL_STYLE: fillStyleEnum.fill,
    SNAKE_DEFAULT_SEGMENT_TYPE: segmentTypesEnum.rectangle,

    FEED_SIZE: 10,
    FEED_DEFAULT_FILL_STYLE: fillStyleEnum.fill,
    FEED_DEFAULT_TYPE: feedTypesEnum.sphere
};